### ISSUE TITLE
filter by event meta data

### ISSUE THREAD

**Issue by uha4** [pretix/pretix-widget-wordpress#3]
I did not find a way to filter by event meta data as mentioned here:
https://github.com/pretix/pretix/discussions/3580

Is this not yet possible in the wordpress plugin? 
Or did I just not manage to find it?

could you please add this filter or make it more obvious to find it?

as a workaround I was able to use the filter by adding the widget-code in a custom HTML field.

Thanks for the great work...

**Comment by raphaelm** [comment]
I think it's not implemented right now, we'll keep it in mind when we release a new version
